plugins {
    id "com.android.application"
}

android {
    namespace "io.github.zilewang7.smallwindow"
    compileSdk 37

    defaultConfig {
        applicationId "io.github.zilewang7.smallwindow"
        minSdk 36
        targetSdk 36
        versionCode 3
        versionName "1.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    compileOnly "io.github.libxposed:api:102.0.0"
}

dependencies {
    compileOnly files("stubs/inputfilter-stubs.jar")
}
